### PR TITLE
Update and Fix compiler errors on CreateIssue.hs

### PR DESCRIPTION
**Pull request by amitaibu**
#194

### CODE REVIEW

**Comment by amitaibu** [comment]
I'm taking this PR in smaller steps, first it already compiles, however:

1. I didn't know how to transform `(GitHub.simpleOwnerLogin $ GitHub.issueUser issue)` to string
1. When calling `main` the result it:

```
Error: HTTPError (StatusCodeException (Status {statusCode = 422, statusMessage = "Unprocessable Entity"}) [("Server","GitHub.com"),("Date","Sun, 13 Mar 2016 13:30:47 GMT"),("Content-Type","application/json; charset=utf-8"),("Content-Length","157"),("Status","422 Unprocessable Entity"),("X-RateLimit-Limit","5000"),("X-RateLimit-Remaining","4988"),("X-RateLimit-Reset","1457878688"),("X-GitHub-Media-Type","github.v3; param=preview"),("Access-Control-Expose-Headers","ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval"),("Access-Control-Allow-Origin","*"),("Content-Security-Policy","default-src 'none'"),("Strict-Transport-Security","max-age=31536000; includeSubdomains; preload"),("X-Content-Type-Options","nosniff"),("X-Frame-Options","deny"),("X-XSS-Protection","1; mode=block"),("X-GitHub-Request-Id","546D5A58:B8C0:15785C4:56E56B86"),("X-Response-Body-Start","{\"message\":\"Invalid request.\\n\\nFor 'properties/labels', nil is not an array.\",\"documentation_url\":\"https://developer.github.com/v3/issues/#create-an-issue\"}"),("X-Request-URL","POST https://api.github.com:443/repos/amitaibu/csv2github/issues")] (CJ {expose = []}))
```

So it seems the `labels` is sent as nil instead of an empty array.

**Comment by amitaibu** [comment]
Maybe `GitHub.newIssueLabels = Nothing` should be (don't know exactly how) be translated to array instead of null? I'll need some pointer here :)

**Comment by amitaibu** [comment]
@phadej if you get a chance to give it look, and point me to the direction to tackle the other issues

**Comment by phadej** [comment]
Based on `https://developer.github.com/v3/issues/#parameters-2` I'd change

```
data NewIssue = NewIssue {
  newIssueTitle     :: Text
, newIssueBody      :: Maybe Text
, newIssueAssignee  :: Maybe Text
, newIssueMilestone :: Maybe Int
, newIssueLabels    :: Maybe (Vector Text) -- to `Vector Text`
} deriving (Show, Data, Typeable, Eq, Ord, Generic)
```

**Comment by amitaibu** [comment]
> newIssueLabels    :: Maybe (Vector Text) -- to `Vector Text`

So when creating a new issue you would have to set `newIssueLabels` as-well?
Is there a way to keep this as `Maybe` but translate a `Nothing` into an empty array?

**Comment by phadej** [comment]
@amitaibu well, you can leave it as `mempty`.

**Comment by amitaibu** [comment]
Seems that also with `GitHub.newIssueLabels = mempty` we are getting the `For 'properties/labels', nil is not an array` error.

I'll _try_ to dig in :)

**Comment by amitaibu** [comment]
With sure but slow progress... I can see that if I do the following change this will work: 

```diff
instance ToJSON NewIssue where
  toJSON (NewIssue t b a m ls) =
    object
    [ "title"     .= t
    , "body"      .= b
    , "assignee"  .= a
    , "milestone" .= m
-    , "labels"    .= ls ]
+    , "labels"    .= () ]
```

However I'm not sure how to do the conditional because it seems I can't do

```haskell
object
    [ "title"     .= t
-- ...
    , "labels"    .= ls' ]
where ls' = case ls of
           Nothing -> ()
           _ -> ls
```

Am I in the right direction ? :)

**Comment by amitaibu** [comment]
Ok, I was able to have a conditional, by duplicated the toJson [by case](https://github.com/phadej/github/pull/195/files#diff-4522472f9f5fd1b16d051adf11166c03R245)

**Comment by amitaibu** [comment]
Ok, I made it work!

```
*CreateIssue> main
amitaibu opened this issue 2016-03-30 18:36:15 UTC
open with 0 comments

A new issue
```

Ready for review

**Comment by amitaibu** [comment]
The [failing test](https://travis-ci.org/phadej/github/jobs/119611460) is just downloading ghc-7.10.3 that got stuck (but I can't restart that test myself)

**Comment by amitaibu** [comment]
@phadej tests are green :)

**Comment by amitaibu** [comment]
Friendly bump -- just checking if my PR is indeed the best way to do it ;)

**Comment by freizl** [comment]
the fix to example works for me. wonder why it's not yet merged?

**Comment by artemohanjanyan** [comment]
@amitaibu I'd say it's better to do `filter notNull` like it's done for `EditIssue` below `NewIssue`. But I'd merge this PR long time ago anyway. It's clearly a bug.

**Comment by ArturGajowy** [comment]
@phadej I'm considering contributing similar fixes for other samples. I'm though discouraged by this PR not being merged.

Is there any work that needs to be done on this PR, apart from resolving the merge conflict?
Maybe configuring cabal to compile this file?
Would you like me to rebase this on top of master and take over the PR?

What would be the best way to contribute towards fixing the samples?
I'd love to open a small PR fixing the next set of samples, but would first like to see this PR reach its conclusion before I start porting other samples.

Thanks!

**Comment by phadej** [comment]
This probably fall through the cracks. I don't know at which point the conflict was introduced.

**Comment by ArturGajowy** [comment]
@phadej should I attempt to rebase this? Do you have any remarks regarding the CreateIssue.hs sample file?

**Comment by andreasabel** [comment]
@amitaibu and @ArturGajowy : Thanks for your work and interest!  Fixing the broken `samples` is most welcome.
This PR is continued at:
- #477

**Pull request closed without merging**
